#!/usr/bin/env bash
# Patch 3: pinned brand header (slogan + logo + VALHALLA word) in the top bar of the home screen.
# The images are embedded into the Kotlin code (not into Compose resources), so they cannot go missing at runtime.
set -euo pipefail
cd "$(dirname "$0")/../../YPtun"
python3 - <<'PY'
import base64, glob, io
from PIL import Image

# pick the images in branding/ by their shape: logo ~ 1.0-1.7 wide, slogan > 3.5 wide
logo = slogan = None
for f in sorted(glob.glob('../branding/*.jpg') + glob.glob('../branding/*.jpeg') + glob.glob('../branding/*.png')):
    w, h = Image.open(f).size
    r = w / h
    if logo is None and 1.0 <= r <= 1.7:
        logo = f
    elif slogan is None and r > 3.5:
        slogan = f

def segments(flags, min_len=4):
    segs, start = [], None
    for y, on in enumerate(flags + [False]):
        if on and start is None: start = y
        if not on and start is not None:
            if y - start >= min_len: segs.append((start, y))
            start = None
    return segs

def png_b64(im, height):
    w = max(1, round(im.width * height / im.height))
    buf = io.BytesIO()
    im.resize((w, height), Image.LANCZOS).save(buf, 'PNG', optimize=True)
    return base64.b64encode(buf.getvalue()).decode()

blank = png_b64(Image.new('RGB', (2, 2), (0, 0, 0)), 2)
tri = word = blank
if logo:
    im = Image.open(logo).convert('RGB')
    mask = im.convert('L').point(lambda p: 255 if p > 45 else 0)
    flags = [mask.crop((0, y, im.width, y + 1)).getbbox() is not None for y in range(im.height)]
    segs = segments(flags)
    assert len(segs) >= 2, 'could not split the logo into triangle and word'
    _, gi = max((segs[i + 1][0] - segs[i][1], i) for i in range(len(segs) - 1))
    def part(rows, extra_bottom=0, pad=14):
        sub = im.crop((0, rows[0], im.width, min(im.height, rows[1] + extra_bottom)))
        bb = mask.crop((0, rows[0], im.width, rows[1])).getbbox()
        return sub.crop((max(0, bb[0] - pad), 0, min(im.width, bb[2] + pad), sub.height))
    tri = png_b64(part((segs[0][0], segs[gi][1])), 108)
    word = png_b64(part((segs[gi + 1][0], segs[-1][1]), extra_bottom=40), 72)
    print('logo split from', logo)
sl = blank
if slogan:
    im = Image.open(slogan).convert('RGB')
    bb = im.convert('L').point(lambda p: 255 if p > 45 else 0).getbbox()
    im = im.crop((max(0, bb[0] - 8), max(0, bb[1] - 8), min(im.width, bb[2] + 8), min(im.height, bb[3] + 8)))
    sl = png_b64(im, 48)
    print('slogan from', slogan)

def kt_list(data, size=16000):
    parts = [data[i:i + size] for i in range(0, len(data), size)] or ['']
    return 'listOf(\n' + ',\n'.join('        "' + p + '"' for p in parts) + '\n    )'

images = ('package org.olcbox.app.ui.features.home.components\n\n'
          '// Generated by branding/patches/03-header.sh: the header pictures as base64 PNG.\n'
          'internal object ValhallaHeaderImages {\n'
          '    val slogan = ' + kt_list(sl) + '\n'
          '    val triangle = ' + kt_list(tri) + '\n'
          '    val word = ' + kt_list(word) + '\n}\n')
comp = '''package org.olcbox.app.ui.features.home.components

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.dp
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import org.jetbrains.compose.resources.decodeToImageBitmap

@OptIn(ExperimentalEncodingApi::class)
private fun decodeHeaderImage(parts: List<String>): ImageBitmap =
    Base64.decode(parts.joinToString("")).decodeToImageBitmap()

/** Pinned brand header: slogan on top, logo and the VALHALLA word below (images on a black background). */
@Composable
fun ValhallaHeader() {
    val slogan = remember { decodeHeaderImage(ValhallaHeaderImages.slogan) }
    val triangle = remember { decodeHeaderImage(ValhallaHeaderImages.triangle) }
    val word = remember { decodeHeaderImage(ValhallaHeaderImages.word) }
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Image(
            bitmap = slogan,
            contentDescription = null,
            modifier = Modifier.height(14.dp),
            contentScale = ContentScale.Fit
        )
        Row(
            modifier = Modifier.padding(top = 2.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Image(
                bitmap = triangle,
                contentDescription = null,
                modifier = Modifier.height(32.dp),
                contentScale = ContentScale.Fit
            )
            Image(
                bitmap = word,
                contentDescription = "Valhalla",
                modifier = Modifier.height(22.dp),
                contentScale = ContentScale.Fit
            )
        }
    }
}
'''
d = 'sharedUI/src/commonMain/kotlin/org/olcbox/app/ui/features/home/components/'
open(d + 'ValhallaHeaderImages.kt', 'w', encoding='utf-8').write(images)
open(d + 'ValhallaHeader.kt', 'w', encoding='utf-8').write(comp)

# put it into the top bar title
p = d + 'HomeScreenAppBar.kt'
s = open(p, encoding='utf-8').read()
if 'ValhallaHeader()' not in s:
    done = False
    for name in ('Valhalla', 'YPtun'):
        old = ('        title = {\n            Text(\n                text = "' + name + '",\n'
               '                style = MaterialTheme.typography.titleLarge,\n'
               '                color = MaterialTheme.colorScheme.onSurface\n            )\n        },\n')
        if old in s:
            s = s.replace(old, '        title = { ValhallaHeader() },\n'); done = True; break
    assert done, 'top bar title block not found'
    open(p, 'w', encoding='utf-8').write(s)
    print('header placed in the top bar')
PY
echo "patch 3 done"
